import { useEffect, useState } from "react";
import { Download } from "lucide-react";
import Swal from "sweetalert2";
import { getEventLeadsReport, exportEventLeadsReport, getEventLeadsReportEvents } from "@/services/eventService";
import { formatDateTime } from "@/utils/tz";

const GREEN = "var(--secondary)";

// Color for each event status label used in the report.
const STATUS_COLOR = {
    Active: "#2f9e3a",
    Scheduled: "var(--secondary-text)",
    Inactive: "#B0592E",
    Expired: "#B0592E",
    Deleted: "#8a3f1e",
};
const statusColor = (label) => STATUS_COLOR[label] || "var(--muted-foreground)";

// Dates shown in the deployment timezone (not the browser's).
const fmtDate = (iso) => formatDateTime(iso) || "—";

/**
 * Event → leads report, rendered inline (in place of the events table) rather
 * than in a modal. Shows, per event, the leads generated by that event's
 * attendees, filterable by event (select) and by a date range, exportable to
 * Excel.
 */
export const LeadsReportView = () => {
    const [filters, setFilters] = useState({ event: "", date_from: "", date_to: "" });
    const [data, setData] = useState({ rows: [], count: 0, by_pipeline: {}, selected_event: null });
    const [reportEvents, setReportEvents] = useState([]);   // all events that generated leads (+status)
    const [loading, setLoading] = useState(true);
    const [exporting, setExporting] = useState(false);

    const load = async (f = filters) => {
        setLoading(true);
        try {
            const res = await getEventLeadsReport(f);
            setData({
                rows: Array.isArray(res.rows) ? res.rows : [],
                count: res.count || 0,
                by_pipeline: res.by_pipeline || {},
                selected_event: res.selected_event || null,
            });
        } catch (e) {
            Swal.fire({ icon: "error", title: "Could not load report", text: e.message });
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        getEventLeadsReportEvents()
            .then((list) => setReportEvents(Array.isArray(list) ? list : []))
            .catch(() => {});
        load(filters);
        /* eslint-disable-next-line react-hooks/exhaustive-deps */
    }, []);

    const setFilter = (k, v) => setFilters((f) => ({ ...f, [k]: v }));

    const apply = () => load(filters);
    const reset = () => {
        const cleared = { event: "", date_from: "", date_to: "" };
        setFilters(cleared);
        load(cleared);
    };

    const doExport = async () => {
        setExporting(true);
        try {
            await exportEventLeadsReport(filters);
        } catch (e) {
            Swal.fire({ icon: "error", title: "Export failed", text: e.message });
        } finally {
            setExporting(false);
        }
    };

    const inputCls = "h-10 px-3 rounded-lg text-sm";
    const inputStyle = { border: "1px solid var(--border)", backgroundColor: "var(--background)", color: "var(--foreground)" };
    const labelStyle = { color: "var(--foreground)", fontSize: 12, fontWeight: 600, display: "block", marginBottom: 4 };
    const th = "px-3 py-2 text-xs font-semibold text-left";

    // Event status column only shows when a single event is selected (derived
    // from the LOADED data, not the pending filter); on "All events" it's
    // hidden (per requirement).
    const showStatus = !!data.selected_event;
    const colCount = showStatus ? 7 : 6;

    return (
        <div className="overflow-hidden" style={{ borderRadius: "10px", border: "1px solid var(--border)", backgroundColor: "var(--background)" }}>
            <div className="px-5 py-3 flex items-center gap-2" style={{ borderBottom: "1px solid var(--border)", backgroundColor: "var(--card)" }}>
                <span className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>Event leads report</span>
                <span className="ml-1 text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "rgba(37,91,1,0.12)", color: "var(--secondary-text)", border: "1px solid rgba(37,91,1,0.3)" }}>
                    {data.count}
                </span>
                <span className="ml-2 text-xs" style={{ color: "#9b948e" }}>leads generated by attendees</span>
            </div>

            <div className="p-4 space-y-4">
                {/* Filters */}
                <div className="flex flex-wrap items-end gap-3 p-3 rounded-lg" style={{ backgroundColor: "var(--muted)", border: "1px solid var(--border)" }}>
                    <div className="min-w-[200px] flex-1">
                        <label style={labelStyle}>Event</label>
                        <select className={`${inputCls} w-full`} style={inputStyle} value={filters.event} onChange={(e) => setFilter("event", e.target.value)}>
                            <option value="">All events</option>
                            {reportEvents.map((ev) => (
                                <option key={ev.id} value={ev.id}>
                                    {ev.name}{ev.status_label ? ` — ${ev.status_label}` : ""}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label style={labelStyle}>From</label>
                        <input type="date" className={inputCls} style={inputStyle} value={filters.date_from} onChange={(e) => setFilter("date_from", e.target.value)} />
                    </div>
                    <div>
                        <label style={labelStyle}>To</label>
                        <input type="date" className={inputCls} style={inputStyle} value={filters.date_to} onChange={(e) => setFilter("date_to", e.target.value)} />
                    </div>
                    <button type="button" onClick={apply} className="h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer" style={{ backgroundColor: GREEN, color: "var(--secondary-foreground)" }}>
                        Apply
                    </button>
                    <button type="button" onClick={reset} className="h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer" style={{ border: "1px solid var(--border)", color: "var(--muted-foreground)", backgroundColor: "var(--background)" }}>
                        Reset
                    </button>
                    <button
                        type="button"
                        onClick={doExport}
                        disabled={exporting || data.count === 0}
                        className="ml-auto flex items-center gap-2 h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer"
                        style={{
                            border: `1px solid ${data.count === 0 ? "var(--border)" : "var(--secondary-text)"}`,
                            color: data.count === 0 ? "color-mix(in srgb, var(--muted-foreground) 45%, transparent)" : "var(--secondary-text)",
                            backgroundColor: "var(--background)",
                            cursor: data.count === 0 ? "not-allowed" : "pointer",
                        }}
                    >
                        <Download className="h-4 w-4" /> {exporting ? "Exporting…" : "Export to Excel"}
                    </button>
                </div>

                {/* Summary */}
                <div className="flex flex-wrap items-center gap-2 text-sm" style={{ color: "var(--foreground)" }}>
                    <span className="font-semibold">{data.count}</span>
                    <span style={{ color: "#9b948e" }}>lead{data.count === 1 ? "" : "s"} generated</span>
                    {/* Selected event's status — only when a single event is chosen. */}
                    {data.selected_event?.status_label && (
                        <span
                            className="text-xs font-semibold px-2 py-0.5 rounded-full"
                            style={{
                                backgroundColor: `color-mix(in srgb, ${statusColor(data.selected_event.status_label)} 12%, transparent)`,
                                color: statusColor(data.selected_event.status_label),
                                border: `1px solid color-mix(in srgb, ${statusColor(data.selected_event.status_label)} 33%, transparent)`,
                            }}
                        >
                            {data.selected_event.name}: {data.selected_event.status_label}
                        </span>
                    )}
                    {Object.entries(data.by_pipeline).map(([name, n]) => (
                        <span key={name} className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "rgba(37,91,1,0.12)", color: "var(--secondary-text)" }}>
                            {name}: {n}
                        </span>
                    ))}
                </div>

                {/* Table */}
                <div className="overflow-auto rounded-lg" style={{ border: "1px solid var(--border)" }}>
                    <table className="w-full text-sm">
                        <thead>
                            <tr style={{ backgroundColor: GREEN }}>
                                {["Event", "Modality", ...(showStatus ? ["Event status"] : []), "Lead", "Pipeline", "Stage", "Generated on"].map((h) => (
                                    <th key={h} className={th} style={{ color: "var(--secondary-foreground)" }}>{h}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody style={{ color: "var(--foreground)" }}>
                            {loading ? (
                                <tr><td colSpan={colCount} className="px-3 py-8 text-center" style={{ color: "#9b948e" }}>Loading…</td></tr>
                            ) : data.rows.length === 0 ? (
                                <tr><td colSpan={colCount} className="px-3 py-8 text-center" style={{ color: "#9b948e" }}>No leads found for these filters.</td></tr>
                            ) : (
                                data.rows.map((r, i) => (
                                    <tr key={i} style={{ borderBottom: "1px solid var(--border)" }}>
                                        <td className="px-3 py-2">{r.event || "—"}</td>
                                        <td className="px-3 py-2">
                                            <span className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "var(--card)", color: "var(--muted-foreground)" }}>{r.modality || "—"}</span>
                                        </td>
                                        {showStatus && (
                                            <td className="px-3 py-2">
                                                <span className="text-xs font-semibold px-2 py-0.5 rounded-full" style={{ backgroundColor: `color-mix(in srgb, ${statusColor(r.event_status)} 12%, transparent)`, color: statusColor(r.event_status), border: `1px solid color-mix(in srgb, ${statusColor(r.event_status)} 33%, transparent)` }}>
                                                    {r.event_status || "—"}
                                                </span>
                                            </td>
                                        )}
                                        <td className="px-3 py-2 font-medium">{r.lead_name || "—"}</td>
                                        <td className="px-3 py-2" style={{ color: "var(--muted-foreground)" }}>{r.pipeline || "—"}</td>
                                        <td className="px-3 py-2">
                                            <span className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "rgba(37,91,1,0.12)", color: "var(--secondary-text)" }}>{r.stage || "—"}</span>
                                        </td>
                                        <td className="px-3 py-2" style={{ color: "var(--muted-foreground)" }}>{fmtDate(r.generated_at)}</td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};
