import { useEffect, useState } from "react";
import { X, Download, BarChart3 } from "lucide-react";
import Swal from "sweetalert2";
import { getEventLeadsReport, exportEventLeadsReport } from "@/services/eventService";

const GREEN = "#5E6A43";

const fmtDate = (iso) => {
    if (!iso) return "—";
    const d = new Date(iso);
    if (isNaN(d)) return "—";
    return d.toLocaleString("en-US", {
        month: "short", day: "2-digit", year: "numeric",
        hour: "2-digit", minute: "2-digit", hour12: false,
    });
};

/**
 * Event → leads report. Shows, per event, the leads generated by that event's
 * attendees (lead name + pipeline + stage + generation date), filterable by
 * event (select) and by a date range, and exportable to Excel.
 */
export const LeadsReportModal = ({ events = [], onClose }) => {
    const [filters, setFilters] = useState({ event: "", date_from: "", date_to: "" });
    const [data, setData] = useState({ rows: [], count: 0, by_pipeline: {} });
    const [loading, setLoading] = useState(true);
    const [exporting, setExporting] = useState(false);

    const load = async (f = filters) => {
        setLoading(true);
        try {
            const res = await getEventLeadsReport(f);
            setData({
                rows: Array.isArray(res.rows) ? res.rows : [],
                count: res.count || 0,
                by_pipeline: res.by_pipeline || {},
            });
        } catch (e) {
            Swal.fire({ icon: "error", title: "Could not load report", text: e.message });
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { load(filters); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);

    const setFilter = (k, v) => setFilters((f) => ({ ...f, [k]: v }));

    const apply = () => load(filters);
    const reset = () => {
        const cleared = { event: "", date_from: "", date_to: "" };
        setFilters(cleared);
        load(cleared);
    };

    const doExport = async () => {
        setExporting(true);
        try {
            await exportEventLeadsReport(filters);
        } catch (e) {
            Swal.fire({ icon: "error", title: "Export failed", text: e.message });
        } finally {
            setExporting(false);
        }
    };

    const inputCls = "h-10 px-3 rounded-lg text-sm";
    const inputStyle = { border: "1px solid #D8D2C4", backgroundColor: "#FFFFFF", color: "#2E2A26" };
    const labelStyle = { color: "#2E2A26", fontSize: 12, fontWeight: 600, display: "block", marginBottom: 4 };
    const th = "px-3 py-2 text-xs font-semibold text-left";

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ backgroundColor: "rgba(0,0,0,0.4)" }}>
            <div className="w-full max-w-5xl rounded-2xl p-6 space-y-4 max-h-[92vh] overflow-auto" style={{ backgroundColor: "#FBF7EF", fontFamily: '"Source Sans 3", Arial, sans-serif' }}>
                {/* Header */}
                <div className="flex items-start justify-between gap-4">
                    <div className="flex items-center gap-2">
                        <BarChart3 className="h-5 w-5" style={{ color: GREEN }} />
                        <div>
                            <h2 className="text-lg font-semibold" style={{ color: "#2E2A26" }}>Event leads report</h2>
                            <p className="text-xs" style={{ color: "#9b948e" }}>Leads generated by each event's attendees.</p>
                        </div>
                    </div>
                    <button type="button" onClick={onClose} className="shrink-0 cursor-pointer" style={{ color: "#6b6560" }} title="Close">
                        <X className="h-5 w-5" />
                    </button>
                </div>

                {/* Filters */}
                <div className="flex flex-wrap items-end gap-3 p-3 rounded-lg" style={{ backgroundColor: "#F5F0E8", border: "1px solid #E7E1D4" }}>
                    <div className="min-w-[200px] flex-1">
                        <label style={labelStyle}>Event</label>
                        <select className={`${inputCls} w-full`} style={inputStyle} value={filters.event} onChange={(e) => setFilter("event", e.target.value)}>
                            <option value="">All events</option>
                            {events.map((ev) => (
                                <option key={ev.id} value={ev.id}>{ev.name}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label style={labelStyle}>From</label>
                        <input type="date" className={inputCls} style={inputStyle} value={filters.date_from} onChange={(e) => setFilter("date_from", e.target.value)} />
                    </div>
                    <div>
                        <label style={labelStyle}>To</label>
                        <input type="date" className={inputCls} style={inputStyle} value={filters.date_to} onChange={(e) => setFilter("date_to", e.target.value)} />
                    </div>
                    <button type="button" onClick={apply} className="h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer" style={{ backgroundColor: GREEN, color: "#FBF7EF" }}>
                        Apply
                    </button>
                    <button type="button" onClick={reset} className="h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer" style={{ border: "1px solid #D8D2C4", color: "#6b6560", backgroundColor: "#FFFFFF" }}>
                        Reset
                    </button>
                    <button
                        type="button"
                        onClick={doExport}
                        disabled={exporting || data.count === 0}
                        className="ml-auto flex items-center gap-2 h-10 px-4 rounded-lg text-sm font-semibold cursor-pointer"
                        style={{
                            border: `1px solid ${data.count === 0 ? "#D8D2C4" : GREEN}`,
                            color: data.count === 0 ? "#c9c3b6" : GREEN,
                            backgroundColor: "#FFFFFF",
                            cursor: data.count === 0 ? "not-allowed" : "pointer",
                        }}
                    >
                        <Download className="h-4 w-4" /> {exporting ? "Exporting…" : "Export to Excel"}
                    </button>
                </div>

                {/* Summary */}
                <div className="flex flex-wrap items-center gap-2 text-sm" style={{ color: "#2E2A26" }}>
                    <span className="font-semibold">{data.count}</span>
                    <span style={{ color: "#9b948e" }}>lead{data.count === 1 ? "" : "s"} generated</span>
                    {Object.entries(data.by_pipeline).map(([name, n]) => (
                        <span key={name} className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "rgba(94,106,67,0.12)", color: GREEN }}>
                            {name}: {n}
                        </span>
                    ))}
                </div>

                {/* Table */}
                <div className="overflow-auto rounded-lg" style={{ border: "1px solid #D8D2C4", maxHeight: "50vh" }}>
                    <table className="w-full text-sm">
                        <thead>
                            <tr style={{ backgroundColor: GREEN, position: "sticky", top: 0 }}>
                                {["Event", "Modality", "Lead", "Pipeline", "Stage", "Generated on"].map((h) => (
                                    <th key={h} className={th} style={{ color: "#FBF7EF" }}>{h}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody style={{ color: "#2E2A26" }}>
                            {loading ? (
                                <tr><td colSpan={6} className="px-3 py-8 text-center" style={{ color: "#9b948e" }}>Loading…</td></tr>
                            ) : data.rows.length === 0 ? (
                                <tr><td colSpan={6} className="px-3 py-8 text-center" style={{ color: "#9b948e" }}>No leads found for these filters.</td></tr>
                            ) : (
                                data.rows.map((r, i) => (
                                    <tr key={i} style={{ borderBottom: "1px solid #D8D2C4" }}>
                                        <td className="px-3 py-2">{r.event || "—"}</td>
                                        <td className="px-3 py-2">
                                            <span className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "#F2EBDD", color: "#6b6560" }}>{r.modality || "—"}</span>
                                        </td>
                                        <td className="px-3 py-2 font-medium">{r.lead_name || "—"}</td>
                                        <td className="px-3 py-2" style={{ color: "#6b6560" }}>{r.pipeline || "—"}</td>
                                        <td className="px-3 py-2">
                                            <span className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "rgba(94,106,67,0.12)", color: GREEN }}>{r.stage || "—"}</span>
                                        </td>
                                        <td className="px-3 py-2" style={{ color: "#6b6560" }}>{fmtDate(r.generated_at)}</td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};
