// Locale options for the "Number format" picker in the attribute config.
//
// Same reasoning as currencies.js: the examples are generated by Intl at
// render time rather than hard-coded, so each option shows exactly what the
// number will look like instead of asking an admin to know what "es-CR"
// does to a thousands separator.
//
// The list is curated rather than exhaustive (Intl knows hundreds). It covers
// the markets this product is sold in plus the majors — and an existing value
// that is not on the list is never dropped, see localeOptions below.

const CODES = [
    // Central America and the Caribbean
    "es-CR", "es-PA", "es-NI", "es-HN", "es-GT", "es-SV", "es-DO",
    // North America
    "en-US", "es-MX", "en-CA", "fr-CA",
    // South America
    "es-CO", "es-PE", "es-CL", "es-AR", "es-UY", "es-BO", "es-PY", "es-VE", "pt-BR",
    // Europe and beyond
    "es-ES", "en-GB", "pt-PT", "fr-FR", "de-DE", "it-IT", "nl-NL", "ja-JP", "zh-CN",
];

const SAMPLE = 1234567.89;

// What this locale does to a number, e.g. "1 234 567,89". Falls back to the
// bare code if Intl has no data for it, so an option is never blank.
export const localeSample = (code) => {
    try {
        return SAMPLE.toLocaleString(code, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        });
    } catch {
        return "";
    }
};

const regionNames = typeof Intl !== "undefined" && Intl.DisplayNames
    ? new Intl.DisplayNames(["en"], { type: "region" })
    : null;

const languageNames = typeof Intl !== "undefined" && Intl.DisplayNames
    ? new Intl.DisplayNames(["en"], { type: "language" })
    : null;

const describe = (code) => {
    const [lang, region] = code.split("-");
    try {
        const l = languageNames?.of(lang) || lang;
        const r = region ? regionNames?.of(region) || region : "";
        return r ? `${l} (${r})` : l;
    } catch {
        return code;
    }
};

/**
 * [{ value, label }] for the picker. `current` is whatever the attribute has
 * stored: if it is a tag outside the curated list (set through the API, or
 * left over from when this was a free-text field) it is prepended so that
 * opening the form does not silently reset it to "follow the viewer".
 */
export const localeOptions = (current) => {
    const codes = [...CODES];
    const tag = typeof current === "string" ? current.trim() : "";
    if (tag && !codes.includes(tag)) codes.unshift(tag);

    return codes.map((code) => {
        const sample = localeSample(code);
        return {
            value: code,
            label: sample ? `${code} — ${sample}` : code,
            title: describe(code),
        };
    });
};
